[package]
name = "waqas"
version = "0.1.0"
authors = ["waqas <waqaskhitran270@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assignment7_lib = {path = "../assignment7_lib"}
